name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Se ejecuta todos los días a la medianoche

  workflow_dispatch:  # Permite ejecutarlo manualmente

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v3

      - name: Generar la animación de la serpiente
        uses: Platane/snk@v3
        with:
          github_user_name: DanielDev87
          outputs: dist/snake.svg

      - name: Subir animación al repositorio
        uses: actions/upload-artifact@v3
        with:
          name: snake
          path: dist/snake.svg
