name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Ejecuta el workflow todos los días a medianoche
  workflow_dispatch: # Permite ejecutar el workflow manualmente

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/github-snake.svg

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-snake
          path: dist/github-snake.svg

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
