name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Se ejecuta todos los días a la medianoche
  workflow_dispatch:  # Permite ejecutarlo manualmente desde la pestaña Actions

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v3

      - name: Generar la animación de la serpiente
        uses: Platane/snk@v3
        with:
          github_user_name: DanielDev87
          outputs: dist/snake.svg

      - name: Publicar animación en la rama "output"
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
