name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"  # Se ejecuta todos los días a la medianoche
  workflow_dispatch:  # Permite ejecutarlo manualmente desde la pestaña Actions

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v3

      - name: Generar la animación de la serpiente
        uses: Platane/snk@v3
        with:
          github_user_name: DanielDev87
          outputs: dist/snake.svg

      - name: Commit y push de la animación
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          mkdir -p assets
          mv dist/snake.svg assets/snake.svg
          git add assets/snake.svg
          git commit -m "Actualización de la animación de la serpiente" || echo "Sin cambios para commit"
          git push
